Repository Marama-App/marama, pull requests merged in 2018-05, with the labels that each got.

#189 Add course data - dancing
  test/server/db/seeds/02_interest_types.js
  test/server/db/seeds/04_study.js
Labels: dancing, data

#180 Responsive nav
  server/public/css/nav.css
Labels: enhancement, styling

#198 Database to Deployment
  test/server/db/seeds/06_grants.js
  test/server/db/seeds/14_grants_study_junction.js
Labels: maintenance

#201 Url spacing fix
  client/components/Interest.jsx
  client/components/Jobs.jsx
  client/components/Study.jsx
  client/components/Type.jsx
  test/server/db/seeds/02_interest_types.js
  test/server/db/seeds/04_study.js
  test/server/db/seeds/11_types_study_junction.js
Labels: maintenance

#204 Deployment to Master
  client/components/Contact.jsx
Labels: maintenance

#207 Contact form now able to submit
  .github/PULL_REQUESTS.md
  client/components/Contact.jsx
  client/lib/base-url.js
  client/webpack.common.js
  client/webpack.dev.js
  client/webpack.prod.js
  package.json
  server/public/images/marama-db.jpg
  server/public/images/marama-thumbnail.png
  server/public/index.html
  server/routes/contact.js
  sound-data.json
  test/server/db/seeds/02_interest_types.js
  test/server/db/seeds/04_study.js
  test/server/db/seeds/13_location_study_junction.js
  yarn.lock
Labels: bug

#209 Fix position of 'Thanks for submitting' on contact page
  client/components/Contact.jsx
  client/components/Grants.jsx
  server/public/css/contact.css
Labels: styling

#210 Dev to master
  client/components/Contact.jsx
  client/components/Grants.jsx
  server/public/css/contact.css
Labels: styling

#212 Wording doesn't apply universally
  client/components/Interest.jsx
  client/components/Jobs.jsx
  test/server/db/seeds/02_interest_types.js
Labels: enhancement
